### ISSUE TITLE
有部署教程吗

### ISSUE THREAD

**Issue by lingxyun** [maomao1996/vitepress-nav-template#2]

**Comment by maomao1996** [comment]
如果需要部署到 GitHub Pages 可以看这个 [使用 GitHub Actions 自动部署
](https://notes.fe-mm.com/workflow/git/#%E4%BD%BF%E7%94%A8-github-actions-%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2)

也可以使用其他第三方的部署 [netlify](https://www.netlify.com/) 或者 [vercel](https://vercel.com/)
