### ISSUE TITLE
raindown 变量变色样式不生效

### ISSUE THREAD

**Issue by beao-y** [maomao1996/vitepress-nav-template#23]
md中，a连接颜色时有时无，导航中 hover 边框色也是错乱的

**Comment by maomao1996** [comment]
> md中，a连接颜色时有时无，导航中 hover 边框色也是错乱的

这是因为已经浏览过的链接会被 `:visited` 匹配，而这个选择器下的 `color` 相关样式规则不支持 css 变量

**Comment by beao-y** [comment]
原来如此，感谢解答
