### ISSUE TITLE
http链接无法随着主题变色

### ISSUE THREAD

**Issue by nine0703** [maomao1996/vitepress-nav-template#28]
https链接可以随着主题变色，但是http链接无法随着主题变色，请问如何设置两者都变色？
![捕获](https://github.com/user-attachments/assets/9d854a69-ea1c-48be-9919-66c45d434be3)
![1捕获](https://github.com/user-attachments/assets/1fb2c55f-e176-41cb-95a8-250b613b97d6)

**Comment by maomao1996** [comment]
应该是你的 `http` 链接有访问记录，`https` 的链接没有访问记录，具体原因看这个 #23

**Comment by nine0703** [comment]
尝试了看文档，搜索:visited伪类选择，搜索:root，搜索http和https，，依然不知道如何调整，可以麻烦再详细些吗？谢谢作者！

**Comment by maomao1996** [comment]
这个调整不了的，因为被 `:visited` 匹配的元素不支持变色，你要变色就只能把浏览器的历史记录清空（不想清空你可以换个浏览器访问）

**Comment by nine0703** [comment]
好吧，感谢解惑

**Comment by nine0703** [comment]
笑死了，想到一个套娃的笨办法，https是亮的，并且块只做跳转，nginx配置监听https的端口，重定向到http，这样https也是亮的，也能跳转
