### ISSUE TITLE
部署到nginx时，打开页面一闪而过到404

### ISSUE THREAD

**Issue by nine0703** [maomao1996/vitepress-nav-template#29]
根据网上资料，在nginx的配置中添加
![11捕获](https://github.com/user-attachments/assets/8b0c796a-78f2-4768-9610-32367b1036a9)
重启服务后仍让无法正常工作，编译时，采用修改 base: APP_BASE_PATH ? `/${APP_BASE_PATH}/` : '/',  修改为
 base: APP_BASE_PATH ? `/${APP_BASE_PATH}/` : './',的方式编译通过

**Comment by maomao1996** [comment]
这个问题应该是 `cleanUrls` 配置项影响的，你可以参考这里的资料

- [生成简洁的 URL](https://vitepress.dev/zh/guide/routing#generating-clean-url)
- [部署 VitePress 站点 - Nginx](https://vitepress.dev/zh/guide/deploy#nginx)

**Comment by nine0703** [comment]
按照文档的nginx配置，问题已解决，而且我还发现chrome浏览器会强制给你升级https
