### ISSUE TITLE
vitepress 版本更换 Vue版本没有更换

### ISSUE THREAD

**Issue by Git-zaizai** [maomao1996/vitepress-nav-template#3]
vitepress 升级到了 1.0.0-rc.20，运行会报错
![微信截图_20231018094440](https://github.com/maomao1996/vitepress-nav-template/assets/66865928/ba8299d9-082e-48ce-b21c-5248895657a0)
查看原因 Vue要到3.3以上才正确运行

**Comment by maomao1996** [comment]
> vitepress 升级到了 1.0.0-rc.20，运行会报错 ![微信截图_20231018094440](https://user-images.githubusercontent.com/66865928/276050370-ba8299d9-082e-48ce-b21c-5248895657a0.png) 查看原因 Vue要到3.3以上才正确运行

感谢反馈，已经修复

**Comment by maomao1996** [comment]
> 还有大佬发布的模版怎么感觉和您的本站有不一样呢？可以都更新一下不

目前是有部分不太一样，后面有空会更新
