### ISSUE TITLE
有BUG，部署后并没有显示主页

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#30]
https://map.earthvillage.top/EarthVillageWIKI/

具体表现为空白
![image](https://github.com/user-attachments/assets/34b1dfb0-d315-44d9-97ec-3796d0016edd)

**Comment by maomao1996** [comment]
你的这个站点里面都没有 `vitepress` 打包后的代码哦，先检查下你部署的是不是 `vitepress` 打包后的 `dist` 文件夹

**Comment by MinecraftEarthVillage** [comment]
> 你的这个站点里面都没有 打包后的代码哦，先检查下你部署的是不是 打包后的 文件夹`vitepress``vitepress``dist`

![image](https://github.com/user-attachments/assets/55bed8bf-099b-4376-a2ad-31dd1b1b2843)
就这些，我都试过了，都不行

**Comment by maomao1996** [comment]
你这部署的分支和文件夹都不对，好好看一下 README 里面的说明

**配置 Pages 的 Branch 为 `gh-pages` 分支，文件夹为 `/(root)`**
