### ISSUE TITLE
求助，直接下载ZIP解压再上传没有gh-page了怎么办

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#31]
![image](https://github.com/user-attachments/assets/a91f2bd0-2bcd-44bb-a218-cf09a1f664a4)
没使用分叉，我直接下载压缩包的，等我发上去发现没有gh-page了怎么回事啊

前端新手，不敢乱动设置···

**Comment by maomao1996** [comment]
手动触发 `Actions` 下的 `GitHub Actions Build and Deploy` 任务

**Comment by MinecraftEarthVillage** [comment]
> 手动触发 下的 任务`Actions``GitHub Actions Build and Deploy`

有gh-pages了，但是页面失去了样式？
![image](https://github.com/user-attachments/assets/271524e3-d285-4f9f-921b-4e9efa6bd799)
地址是https://lezi.earthvillage.top/

**Comment by maomao1996** [comment]
设置 `base` 为 `/` https://vitepress.dev/zh/reference/site-config#base

**Comment by MinecraftEarthVillage** [comment]
> 设置 为 https://vitepress.dev/zh/reference/site-config#base`base``/`

哪里的设置项目？

**Comment by MinecraftEarthVillage** [comment]
![image](https://github.com/user-attachments/assets/73799d1c-7b11-4047-9511-56ef8872d289)
???????????
