### ISSUE TITLE
未知BUG，添加自定义域名，可构建，无法访问（404）。移除自定义域名，不可构建，无法访问

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#32]
![image](https://github.com/user-attachments/assets/f6ef9ea9-42ff-4e0f-a6e2-d78a53d8bda8)
![image](https://github.com/user-attachments/assets/4f615eb3-36f5-4c3e-9520-0cfa1867b3df)
![image](https://github.com/user-attachments/assets/bba2fea8-8192-4c8f-afa1-dea3dbb8a126)
搞来搞去现在一设置自定义域名可以完成部署访问404，移除自定义域名直接构建失败，我快疯啦~~最后只能重新下载模板重做了

**Comment by MinecraftEarthVillage** [comment]
删了，已经气死了😭

**Comment by maomao1996** [comment]
自定义域名你要修改 `docs/.vitepress/config.ts` 下的 `base` 为 `/`，默认的 `deploy` 脚本是只支持 `github.io` 的

**Comment by maomao1996** [comment]
如果要自定义域名的话，推荐是使用第三方服务来构建部署

- https://pages.cloudflare.com
- https://www.netlify.com
- https://vercel.com
