### ISSUE TITLE
我老老实实的分叉或是“使用此模板”生成仓库，仍然报这个错

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#33]
文件准备完毕→启动网站→构建中→报错
现在连开始都开始不了了啊啊啊
Error:  Logging at level: debug GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/./docs Destination: /github/workspace/./docs/_site Incremental build: disabled. Enable with --incremental Generating... Generating: JekyllOptionalFrontMatter::Generator finished in 1.2583e-05 seconds. Generating: JekyllReadmeIndex::Generator finished in 6.201e-06 seconds. Generating: Jekyll::Paginate::Pagination finished in 3.557e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 2.3094e-05 seconds. Generating: JekyllDefaultLayout::Generator finished in 1.101e-05 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 7.674e-06 seconds. Rendering: assets/css/style.scss Pre-Render Hooks: assets/css/style.scss Rendering Markup: assets/css/style.scss github-pages 232 | Error: No such file or directory @ dir_chdir0 - /github/workspace/docs 

难道还有次数限制吗？我先前创建的另一个WIKI还在用着呢

**Comment by maomao1996** [comment]
这个是部署脚本内部报错，我刚试过了没问题，你再重新运行下脚本就行

**Comment by MinecraftEarthVillage** [comment]
> 这个是部署脚本内部报错，我刚试过了没问题，你再重新运行下脚本就行

邀请进了仓库，辛苦看下了，实在不行只能放弃新文档了···

**Comment by maomao1996** [comment]
已经[修改了 deploy 脚本](https://github.com/maomao1996/vitepress-nav-template/commit/599c3cd919a36b64a404d62c5448679630960f2b)，你同步下，重新构建就行

**Comment by MinecraftEarthVillage** [comment]
> 已经[修改了 deploy 脚本](https://github.com/maomao1996/vitepress-nav-template/commit/599c3cd919a36b64a404d62c5448679630960f2b)，你同步下，重新构建就行

构建可以了，但是失去了样式，跟昨天一样
https://map.earthvillage.top/lezi/
反正我改了路径···
![image](https://github.com/user-attachments/assets/8f5f4d87-5a3c-4b04-8360-e423f86fb444)
