### ISSUE TITLE
Markdown文件的页面似乎显示不全

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#37]
实例测试http://wiki.earthvillage.top/md/%E8%8F%9C%E5%8D%95/%E8%8F%9C%E5%8D%95

![image](https://github.com/user-attachments/assets/630865a7-fefe-4679-97b4-d784121ce857)

评论区、右侧目录和顶部导航栏都没了

# 预期效果
https://lezi.earthvillage.top/article/%E4%B8%89%E4%BA%BA%E4%BC%A0
![image](https://github.com/user-attachments/assets/8c5acfcf-a893-440e-b2d5-754aeb7f371f)

**Comment by maomao1996** [comment]
页面没有经过 `vitepress` 打包导致没有相关样式，建议先看下 [vitepress 的官方文档](https://vitepress.dev/zh/guide/routing)

**Comment by MinecraftEarthVillage** [comment]
> 页面没有经过 打包导致没有相关样式，建议先看下 [vitepress 的官方文档](https://vitepress.dev/zh/guide/routing)`vitepress`

没看懂，里面并没有提到如何“页面打包”的内容，我还以为都配好的呢
