### ISSUE TITLE
> 页面没有经过 打包导致没有相关样式，建议先看下 [vitepress 的官方文档](https://vitepress.dev/zh/guide/routing)`vitepress`

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [maomao1996/vitepress-nav-template#38]
> 页面没有经过 打包导致没有相关样式，建议先看下 [vitepress 的官方文档](https://vitepress.dev/zh/guide/routing)`vitepress`

非常抱歉···没看懂，里面并没有提到如何“页面打包”的内容，我还以为都配好的呢

到底该编辑哪个文件啊 找不到啊

_Originally posted by @MinecraftEarthVillage in https://github.com/maomao1996/vitepress-nav-template/issues/37#issuecomment-2547354619_

**Comment by maomao1996** [comment]
发你的这个文档是让你去了解 vitepress 的路由结构，你自己页面放哪里该生成什么样的地址你都不了解

这是你提供的
http://wiki.earthvillage.top/md/%E8%8F%9C%E5%8D%95/%E8%8F%9C%E5%8D%95

这是 vitepress 生成的
http://wiki.earthvillage.top/public/md/%E8%8F%9C%E5%8D%95/%E8%8F%9C%E5%8D%95
