### ISSUE TITLE
请问如何渲染md的一级标题？

### ISSUE THREAD

**Issue by postyizhan** [maomao1996/vitepress-nav-template#9]
例如 https://postyizhan.github.io/lezi-wiki/article/xxg%E4%BC%A0

一级标题不会显示在右侧的目录

**Comment by maomao1996** [comment]
这个你看看 [vitepress](https://vitepress.dev/zh/reference/default-theme-config#outline) 的文档就可以了

**Comment by postyizhan** [comment]
https://github.com/postyizhan/lezi-wiki/commit/cdc9815725a447b388acc3395b6ae7782820ee53
我尝试修改了一下，但是没有生效
如 https://postyizhan.github.io/lezi-wiki/article/xxg%E4%BC%A0
您能再指点下吗？

**Comment by maomao1996** [comment]
> [postyizhan@cdc9815](https://github.com/postyizhan/lezi-wiki/commit/cdc9815725a447b388acc3395b6ae7782820ee53) 我尝试修改了一下，但是没有生效 如 [postyizhan.github.io/lezi-wiki/article/xxg%E4%BC%A0](https://postyizhan.github.io/lezi-wiki/article/xxg%E4%BC%A0) 您能再指点下吗？

<img width="184" alt="image" src="https://github.com/maomao1996/vitepress-nav-template/assets/24606443/e5676954-41f6-445b-a1e3-f4644caecde1">

你这都有了哇

**Comment by postyizhan** [comment]
哦是的，抱歉浪费您时间了

**Comment by maomao1996** [comment]
小事
